name: Run Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x] # Define Node.js versions to test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm run test

      - name: Report Sentry Deployment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        run: |
          npx sentry-cli releases new "${{ github.sha }}"
          npx sentry-cli releases set-commits --auto "${{ github.sha }}"
          npx sentry-cli releases finalize "${{ github.sha }}"
          npx sentry-cli releases deploys "${{ github.sha }}" new -e production
