version: 2.1

jobs:
  run-cypress-tests:
    docker:
      - image: cimg/node:18.16.1 # Use Node.js version 18.16.1
    parameters:
      cypress-command:
        type: string
        default: "npx cypress run" # Default command to run Cypress tests
      start-command:
        type: string
        default: "" # Command to start the server (optional)
      working-directory:
        type: string
        default: "." # Default working directory
    steps:
      - checkout

      # Set the working directory
      - run:
          name: Change Working Directory
          command: cd << parameters.working-directory >>

      # Install Node.js dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Optionally start the server if start-command is provided
      - run:
          name: Start Server
          command: |
            if [ -n "<< parameters.start-command >>" ]; then
              << parameters.start-command >> &
            fi
          background: true

      # Wait for the server to be ready
      - run:
          name: Wait for Server
          command: npx wait-on https://code-it-ci-mk9n5qeoi-seankim05s-projects.vercel.app/ # Adjust the URL as needed

      # Run Cypress tests
      - run:
          name: Run Cypress Tests
          command: << parameters.cypress-command >>

workflows:
  version: 2
  test:
    jobs:
      - run-cypress-tests:
          cypress-command: "npx cypress run" # You can override this if needed
          start-command: "npm run build && npm run start" # Server start command
          working-directory: "." # Directory containing the package.json
